export type PublicLang = "hu" | "en" | "de" | "fr";

export const publicLabels = {
  hu: {
    trending: "Népszerű ellentmondások",
    timeline: "Idővonal",
    aiAnalysis: "AI elemzés",
    sources: "Források",
    related: "Hasonló esetek",
    communityVote: "Közösségi szavazás",
    contradictionQuestion: "Ez valódi ellentmondás?",
    old: "Korábban",
    new: "Most",
    views: "megtekintés",
    noSource: "Nincs forrás",
    openVideo: "Videó megnyitása",
    heroTitle: "Hasonlítsd össze a politikai állításokat. Találd meg az ellentmondásokat.",
browseContradictions: "Ellentmondások böngészése",
exploreTopics: "Témák böngészése",
topContradictions: "Top ellentmondások",
yes: "Igen",
no: "Nem",
totalVotes: "Összes szavazat",
oldSource: "Korábbi forrás",
newSource: "Új forrás",
confidence: "Biztonság",
severity: "Súlyosság",
reviewStatus: "Ellenőrzési státusz",
backToContradictions: "Vissza az ellentmondásokhoz",
contradictionTitle: "Politikai ellentmondás",

  },

  en: {
    trending: "Trending contradictions",
    timeline: "Timeline",
    aiAnalysis: "AI analysis",
    sources: "Sources",
    related: "Related contradictions",
    communityVote: "Community vote",
    contradictionQuestion: "Is this a contradiction?",
    old: "Earlier",
    new: "Now",
    views: "views",
    noSource: "No source",
    openVideo: "Open video",
    heroTitle: "Compare political statements. Find contradictions.",
browseContradictions: "Browse contradictions",
exploreTopics: "Explore topics",
topContradictions: "Top contradictions",
yes: "Yes",
no: "No",
totalVotes: "Total votes",
oldSource: "Earlier source",
newSource: "New source",
confidence: "Confidence",
severity: "Severity",
reviewStatus: "Review status",
backToContradictions: "Back to contradictions",
contradictionTitle: "Political contradiction",

  },

  de: {
    trending: "Beliebte Widersprüche",
    timeline: "Zeitlinie",
    aiAnalysis: "KI Analyse",
    sources: "Quellen",
    related: "Ähnliche Fälle",
    communityVote: "Community Abstimmung",
    contradictionQuestion: "Ist das ein Widerspruch?",
    old: "Früher",
    new: "Jetzt",
    views: "Aufrufe",
    noSource: "Keine Quelle",
    openVideo: "Video öffnen",
    heroTitle: "Politische Aussagen vergleichen. Widersprüche finden.",
browseContradictions: "Widersprüche ansehen",
exploreTopics: "Themen entdecken",
topContradictions: "Top-Widersprüche",
yes: "Ja",
no: "Nein",
totalVotes: "Stimmen gesamt",
oldSource: "Frühere Quelle",
newSource: "Neue Quelle",
confidence: "Sicherheit",
severity: "Schweregrad",
reviewStatus: "Prüfstatus",
backToContradictions: "Zurück zu den Widersprüchen",
contradictionTitle: "Politischer Widerspruch",


  },

  fr: {
    trending: "Contradictions populaires",
    timeline: "Chronologie",
    aiAnalysis: "Analyse IA",
    sources: "Sources",
    related: "Cas similaires",
    communityVote: "Vote de la communauté",
    contradictionQuestion: "Est-ce une contradiction ?",
    old: "Avant",
    new: "Maintenant",
    views: "vues",
    noSource: "Aucune source",
    openVideo: "Ouvrir la vidéo",
    heroTitle: "Comparez les déclarations politiques. Trouvez les contradictions.",
browseContradictions: "Parcourir les contradictions",
exploreTopics: "Explorer les sujets",
topContradictions: "Principales contradictions",
yes: "Oui",
no: "Non",
totalVotes: "Votes au total",
oldSource: "Source précédente",
newSource: "Nouvelle source",
confidence: "Confiance",
severity: "Gravité",
reviewStatus: "Statut de révision",
backToContradictions: "Retour aux contradictions",
contradictionTitle: "Contradiction politique",

  },
};